export const movies = [
    {
        title: "Shawshank Redemption",
        trendingNumber:"1.png",
        image: "top-1.webp",
        year: "2004",
        cast: "Vice Ganda, Vic Sotto, Jose Manalo, Coco Martin",
        genre: "Action",
        rating: 10,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium dolor laborum autem ullam ab nihil?",
        type: "Comedy",
        duration: "1hr 3mins",
        groupings:"trending"
    },
    // trending number:
    {
        title: "Shawshank Redemption",
        trendingNumber:"7.png",
        image: "top-8.webp",
        year: "2004",
        cast: "Vice Ganda, Vic Sotto, Jose Manalo, Coco Martin",
        genre: "Action",
        rating: 10,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium dolor laborum autem ullam ab nihil?",
        type: "Comedy",
        duration: "1hr 3mins",
        groupings:"trending"
    },
    

    // trending number ends
    {
        title: "Starwars War X",
        trendingNumber:"2.png",
        image: "top-2.webp",
        year: "2015",
        cast: "Harrison Ford, Gina Alajar, Kris Aquino",
        genre: "Action",
        rating: 16,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium dolor laborum autem ullam ab nihil?",
        type: "Action",
        duration: "1hr 3mins",
        groupings:"trending"
    },
    {
        title: "GRAVITY",
        trendingNumber:"3.png",
        image: "top-3.jpg",
        year: "2004",
        cast: "Anne Curtis, Jhong Hilario, Vhong Navarro",
        genre: "Sci-Fi",
        rating: 18,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium dolor laborum autem ullam ab nihil?",
        type: "danger",
        duration: "1hr 3mins",
        groupings:"trending"
    },
    {
        title: "Captain America",
        trendingNumber:"4.png",
        image: "top-4.webp",
        year: "2004",
        cast: "Sassa Girl, Esnyr, Lottie",
        genre: "Comedy",
        rating: 16,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium dolor laborum autem ullam ab nihil?",
        type: "Action",
        duration: "1hr 3mins",
        groupings:"trending"
    },
    {
        title: "Fast & Furious",
        trendingNumber:"5.png",
        image: "top-5.jpg",
        year: "2004",
        cast: "Boy Abunda, Benjie Paras, Wally Bayola",
        genre: "Sci-Fi",
        rating: 12,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium dolor laborum autem ullam ab nihil?",
        type: "action",
        duration: "1hr 3mins",
        groupings:"trending"
    },
    {
        title: "Cocomelon",
        trendingNumber:"6.png",
        image: "top-6.webp",
        year: "2004",
        cast: "Coco Martin",
        genre: "Sci-Fi",
        rating: 3,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium dolor laborum autem ullam ab nihil?",
        type: "action",
        duration: "1hr 3mins",
        groupings:"trending"
    },
    //Asian
    {
        title: "Shawshank Redemption",
        image: "movie-1.jpg",
        year: "2004",
        cast: "Vice Ganda, Vic Sotto, Jose Manalo, Coco Martin",
        genre: "Comedy",
        rating: 10,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium dolor laborum autem ullam ab nihil?",
        type: "awesome",
        duration: "1hr 3mins",
        groupings:"Asian"
    },
    {
        title: "Starwars War X",
        image: "movie-2.jpg",
        year: "2015",
        cast: "Harrison Ford, Gina Alajar, Kris Aquino",
        genre: "Sci-Fi",
        rating: 16,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium dolor laborum autem ullam ab nihil?",
        type: "positive",
        duration: "1hr 3mins",
        groupings:"Asian"
    },
    {
        title: "GRAVITY",
        image: "movie-3.jpg",
        year: "2004",
        cast: "Anne Curtis, Jhong Hilario, Vhong Navarro",
        genre: "Sci-Fi",
        rating: 18,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium dolor laborum autem ullam ab nihil?",
        type: "danger",
        duration: "1hr 3mins",
        groupings:"Asian"
    },
    {
        title: "Captain America",
        image: "movie-5.jpg",
        year: "2004",
        cast: "Sassa Girl, Esnyr, Lottie",
        genre: "Comedy",
        rating: 16,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium dolor laborum autem ullam ab nihil?",
        type: "Roar Roar",
        duration: "1hr 3mins",
        groupings:"Asian"
    },
    {
        title: "Fast & Furious",
        image: "movie-6.jpg",
        year: "2004",
        cast: "Boy Abunda, Benjie Paras, Wally Bayola",
        genre: "Sci-Fi",
        rating: 12,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium dolor laborum autem ullam ab nihil?",
        type: "action",
        duration: "1hr 3mins",
        groupings:"Asian"
    },
    {
        title: "Cocomelon",
        image: "movie-8.jpg",
        year: "2004",
        cast: "Coco Martin",
        genre: "Comedy",
        rating: 3,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium dolor laborum autem ullam ab nihil?",
        type: "action",
        duration: "1hr 3mins",
        groupings:"Asian"
    },
    //American
    {
        title: "Cocomelon",
        image: "movie-1.jpg",
        year: "2004",
        cast: "Coco Martin",
        genre: "Action",
        rating: 3,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium dolor laborum autem ullam ab nihil?",
        type: "action",
        duration: "1hr 3mins",
        groupings:"American"
    },
    {
        title: "Starwars War X",
        image: "movie-2.jpg",
        year: "2015",
        cast: "Harrison Ford, Gina Alajar, Kris Aquino",
        genre: "Sci-Fi",
        rating: 16,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium dolor laborum autem ullam ab nihil?",
        type: "positive",
        duration: "1hr 3mins",
        groupings:"American"
    },
    {
        title: "GRAVITY",
        image: "movie-3.jpg",
        year: "2004",
        cast: "Anne Curtis, Jhong Hilario, Vhong Navarro",
        genre: "Sci-Fi",
        rating: 18,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium dolor laborum autem ullam ab nihil?",
        type: "danger",
        duration: "1hr 3mins",
        groupings:"American"
    },
    {
        title: "Captain America",
        image: "movie-5.jpg",
        year: "2004",
        cast: "Sassa Girl, Esnyr, Lottie",
        genre: "Comedy",
        rating: 16,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium dolor laborum autem ullam ab nihil?",
        type: "Roar Roar",
        duration: "1hr 3mins",
        groupings:"American"
    },
    {
        title: "Fast & Furious",
        image: "movie-6.jpg",
        year: "2004",
        cast: "Boy Abunda, Benjie Paras, Wally Bayola",
        genre: "Action",
        rating: 12,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium dolor laborum autem ullam ab nihil?",
        type: "action",
        duration: "1hr 3mins",
        groupings:"American"
    },
    {
        title: "Cocomelon",
        image: "movie-8.jpg",
        year: "2004",
        cast: "Coco Martin",
        genre: "Comedy",
        rating: 3,
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium dolor laborum autem ullam ab nihil?",
        type: "action",
        duration: "1hr 3mins",
        groupings:"American"
    },
    
]
